services:
  gridcore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridcore
    hostname: gridcore
    networks:
      - internal
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "subdomain=grind"
      - "traefik.http.routers.gridcore.entrypoints=websecure"
      - "traefik.http.services.gridcore.loadbalancer.server.port=80"

networks:
  internal:
    name: internal
    external: true
